version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wiki
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/wiki
      OPENAI_API_KEY: "your_openai_api_key_here"  # заменить
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
